apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: api-intern
  namespace: aap
  labels:
    team: aap
    komponent: datadeling
spec:
  image: {{image}}
  ingresses:
    - https://aap-api.intern.dev.nav.no
    - https://aap-api.ansatt.dev.nav.no
  kafka:
    pool: nav-dev
  resources:
    limits:
      memory: 8Gi
    requests:
      cpu: 500m
      memory: 4Gi
  azure:
    application:
      enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_16
        tier: db-custom-1-3840
        diskAutoresize: true
        highAvailability: true
        pointInTimeRecovery: true
        databases:
          - name: api
  liveness:
    path: /actuator/live
    initialDelay: 1
    periodSeconds: 1
    failureThreshold: 60
  readiness:
    path: /actuator/ready
    initialDelay: 1
    periodSeconds: 1
    failureThreshold: 60
  prometheus:
    enabled: true
    path: /actuator/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: postmottak-backend
        - application: meldekort-backend
        - application: tilleggsstonader-integrasjoner
          namespace: tilleggsstonader
          cluster: dev-gcp
        - application: azure-token-generator
          namespace: nais
          cluster: dev-gcp
        - application: arena
          namespace: teamarenanais
          cluster: dev-fss
        - application: azure-token-generator # Ikke i prod :)
          namespace: nais
          cluster: dev-gcp
        - application: api
          namespace: aap
        - application: fpabakus
          namespace: teamforeldrepenger
          cluster: dev-fss
        - application: saas-proxy
          namespace: teamcrm
          cluster: dev-gcp
        - application: salesforce
          namespace: teamcrm
          cluster: dev-external
        - application: pensjon-pen-q2
          namespace: pensjon-q2
          cluster: prod-fss
        - application: veilarbportefolje
          namespace: obo
          cluster: dev-gcp
        - application: familie-ef-sak
          namespace: teamfamilie
          cluster: dev-gcp
        - application: modiapersonoversikt-api
          namespace: personoversikt
          cluster: dev-gcp
        - application: behandlingsflyt
          namespace: aap
          cluster: dev-gcp
          permissions:
            roles:
              - "add-data"
    outbound:
      external:
        - host: arenaoppslag.dev-fss-pub.nais.io
        - host: pdl-api.dev-fss-pub.nais.io
      rules:
        - application: behandlingsflyt
        - application: tilgang
  env:
    - name: ARENAOPPSLAG_PROXY_BASE_URL
      value: https://arenaoppslag.dev-fss-pub.nais.io
    - name: ARENAOPPSLAG_SCOPE
      value: api://dev-fss.aap.arenaoppslag/.default
    - name: KELVIN_PROXY_BASE_URL
      value: http://behandlingsflyt
    - name: KELVIN_SCOPE
      value: api://dev-gcp.aap.behandlingsflyt/.default
    - name: INTEGRASJON_PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: INTEGRASJON_PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: INTEGRASJON_TILGANG_URL
      value: http://tilgang
    - name: INTEGRASJON_TILGANG_SCOPE
      value: api://dev-gcp.aap.tilgang/.default
