apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: api-intern
  namespace: aap
  labels:
    team: aap
    komponent: datadeling
spec:
  image: {{image}}
  ingresses:
       - https://aap-api.intern.nav.no
  replicas:
    max: 2
    min: 2
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  azure:
    application:
      enabled: true
  liveness:
    path: /actuator/live
    initialDelay: 1
    periodSeconds: 1
    failureThreshold: 60
  readiness:
    path: /actuator/ready
    initialDelay: 1
    periodSeconds: 1
    failureThreshold: 60
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  prometheus:
    enabled: true
    path: /actuator/metrics
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: tilleggsstonader-integrasjoner
          namespace: tilleggsstonader
          cluster: prod-gcp
        - application: postmottak-backend
        - application: arena
          namespace: teamarenanais
          cluster: prod-fss
    outbound:
      external:
        - host: arenaoppslag.prod-fss-pub.nais.io
      rules:
        - application: behandlingsflyt
  env:
    - name: ARENAOPPSLAG_PROXY_BASE_URL
      value: https://arenaoppslag.prod-fss-pub.nais.io
    - name: ARENAOPPSLAG_SCOPE
      value: api://prod-fss.aap.arenaoppslag/.default
    - name: KELVIN_PROXY_BASE_URL
      value: http://behandlingsflyt
    - name: KELVIN_SCOPE
      value: api://prod-gcp.aap.behandlingsflyt/.default
