apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: api-intern
  namespace: aap
  labels:
    team: aap
    komponent: datadeling
spec:
  image: {{image}}
  ingresses:
       - https://aap-api.intern.nav.no
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  azure:
    application:
      enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_16
        tier: db-custom-1-3840
        diskAutoresize: true
        highAvailability: true
        pointInTimeRecovery: true
        databases:
          - name: api
  liveness:
    path: /actuator/live
    initialDelay: 1
    periodSeconds: 1
    failureThreshold: 60
  readiness:
    path: /actuator/ready
    initialDelay: 1
    periodSeconds: 1
    failureThreshold: 60
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  prometheus:
    enabled: true
    path: /actuator/metrics
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: tilleggsstonader-integrasjoner
          namespace: tilleggsstonader
          cluster: prod-gcp
        - application: postmottak-backend
        - application: innsyn
        - application: arena
          namespace: teamarenanais
          cluster: prod-fss
        - application: api
          namespace: aap
        - application: fpabakus
          namespace: teamforeldrepenger
          cluster: prod-fss
        - application: saas-proxy
          namespace: teamcrm
          cluster: prod-gcp
        - application: salesforce
          namespace: teamcrm
          cluster: prod-external
        - application: behandlingsflyt
          namespace: aap
          cluster: prod-gcp
          permissions:
            roles:
              - "add-data"
        - application: meldekort-backend
    outbound:
      external:
        - host: arenaoppslag.prod-fss-pub.nais.io
        - host: pdl-api.prod-fss-pub.nais.io
      rules:
        - application: behandlingsflyt
        - application: tilgang
  env:
    - name: ARENAOPPSLAG_PROXY_BASE_URL
      value: https://arenaoppslag.prod-fss-pub.nais.io
    - name: ARENAOPPSLAG_SCOPE
      value: api://prod-fss.aap.arenaoppslag/.default
    - name: KELVIN_PROXY_BASE_URL
      value: http://behandlingsflyt
    - name: KELVIN_SCOPE
      value: api://prod-gcp.aap.behandlingsflyt/.default
    - name: INTEGRASJON_PDL_URL
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: INTEGRASJON_PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
    - name: INTEGRASJON_TILGANG_URL
      value: http://tilgang
    - name: INTEGRASJON_TILGANG_SCOPE
      value: api://prod-gcp.aap.tilgang/.default
