apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: api-intern
  namespace: aap
  labels:
    team: aap
    komponent: datadeling
spec:
  image: {{image}}
  ingresses:
    - https://aap-api.intern.dev.nav.no
    - https://aap-api.ansatt.dev.nav.no
  replicas:
    max: 2
    min: 2
  resources:
    limits:
      memory: 8Gi
    requests:
      cpu: 500m
      memory: 4Gi
  azure:
    application:
      enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_16
        tier: db-custom-1-3840
        diskAutoresize: true
        highAvailability: true
        pointInTimeRecovery: true
        databases:
          - name: api
  liveness:
    path: /actuator/live
    initialDelay: 1
    periodSeconds: 1
    failureThreshold: 60
  readiness:
    path: /actuator/ready
    initialDelay: 1
    periodSeconds: 1
    failureThreshold: 60
  prometheus:
    enabled: true
    path: /actuator/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: postmottak-backend
        - application: meldekort-backend
        - application: tilleggsstonader-integrasjoner
          namespace: tilleggsstonader
          cluster: dev-gcp
        - application: azure-token-generator
          namespace: aura
          cluster: dev-gcp
        - application: arena
          namespace: teamarenanais
          cluster: dev-fss
        - application: azure-token-generator # Ikke i prod :)
          namespace: aura
          cluster: dev-gcp
        - application: behandlingsflyt
          namespace: aap
          cluster: dev-gcp
          permissions:
            roles:
              - "add-data"
    outbound:
      external:
        - host: arenaoppslag.dev-fss-pub.nais.io
      rules:
        - application: behandlingsflyt
  env:
    - name: ARENAOPPSLAG_PROXY_BASE_URL
      value: https://arenaoppslag.dev-fss-pub.nais.io
    - name: ARENAOPPSLAG_SCOPE
      value: api://dev-fss.aap.arenaoppslag/.default
    - name: KELVIN_PROXY_BASE_URL
      value: http://behandlingsflyt
    - name: KELVIN_SCOPE
      value: api://dev-gcp.aap.behandlingsflyt/.default
