[versions]
komponenter = "2.0.163"
tilgang = "1.0.240"
behandlingsflyt = "0.0.663"
oppgave = "0.0.215"
arenaoppslag = "0.6.2"
resilience4j = "2.4.0"
prometheus = "1.8.0"

[libraries]
kelvin-server = { module = "no.nav.aap.kelvin:server", version.ref = "komponenter" }
kelvin-infrastructure = { module = "no.nav.aap.kelvin:infrastructure", version.ref = "komponenter" }
kelvin-dbconnect = { module = "no.nav.aap.kelvin:dbconnect", version.ref = "komponenter" }
kelvin-dbmigrering = { module = "no.nav.aap.kelvin:dbmigrering", version.ref = "komponenter" }
kelvin-tidslinje = { module = "no.nav.aap.kelvin:tidslinje", version.ref = "komponenter" }
kelvin-ktor-openapi-generator = { module = "no.nav.aap.kelvin:ktor-openapi-generator", version.ref = "komponenter" }
kelvin-dbtest = { module = "no.nav.aap.kelvin:dbtest", version.ref = "komponenter" }
kelvin-json = { module = "no.nav.aap.kelvin:json", version.ref = "komponenter" }
kelvin-motor = { module = "no.nav.aap.kelvin:motor", version.ref = "komponenter" }
kelvin-motor-api = { module = "no.nav.aap.kelvin:motor-api", version.ref = "komponenter" }
tilgang-plugin = { module = "no.nav.aap.tilgang:plugin", version.ref = "tilgang" }
tilgang-plugin-kontrakt = { module = "no.nav.aap.tilgang:plugin-kontrakt", version.ref = "tilgang" }
behandlingsflyt-kontrakt = { module = "no.nav.aap.behandlingsflyt:kontrakt", version.ref = "behandlingsflyt" }
oppgave-api-kontrakt = { module = "no.nav.aap.oppgave:api-kontrakt", version.ref = "oppgave" }
arenaoppslag-kontrakt = { module = "no.nav.aap.arenaoppslag:kontrakt", version.ref = "arenaoppslag" }

resilience4j-circuitbreaker = { module = "io.github.resilience4j:resilience4j-circuitbreaker", version.ref = "resilience4j" }
resilience4j-kotlin = { module = "io.github.resilience4j:resilience4j-kotlin", version.ref = "resilience4j" }
resilience4j-micrometer = { module = "io.github.resilience4j:resilience4j-micrometer", version.ref = "resilience4j" }

prometheus-metrics-tracer-initializer = { module = "io.prometheus:prometheus-metrics-tracer-initializer", version.ref = "prometheus" }
