CREATE TABLE MELDEKORT_PERIODER_MED_FNR
(
    ID          BIGSERIAL PRIMARY KEY,
    PERSONIDENT VARCHAR(11) NOT NULL,
    PERIODE     DATERANGE   NOT NULL
);

CREATE INDEX idx_meldekort_fnr ON meldekort_perioder_med_fnr (PERSONIDENT);