CREATE TABLE MELDEKORT
(
    ID                BIGSERIAL PRIMARY KEY,
    PERSON_IDENT      VARCHAR(11)                            NOT NULL,
    OPPRETTET_TID     TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MOTTATT_TIDSPUNKT TIMESTAMP(3)                           NOT NULL,
);

CREATE TABLE MELDEPERIODE
(
    ID           BIGSERIAL PRIMARY KEY,
    MELDEKORT_ID BIGINT NOT NULL REFERENCES MELDEKORT (ID)
);

CREATE TABLE MELDEKORT_ARBEIDS_PERIODE
(
    ID              BIGSERIAL PRIMARY KEY,
    MELDEPERIODE_ID BIGINT        NOT NULL REFERENCES MELDEPERIODE (ID),
    ARBEIDS_PERIODE DATERANGE     NOT NULL,
    TIMER_ARBEIDET  NUMERIC(5, 2) NOT NULL
)
