CREATE TABLE MELDEKORT
(
    ID                     BIGSERIAL PRIMARY KEY,
    PERSON_IDENT           VARCHAR(11)                            NOT NULL,
    OPPRETTET_TID          TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    INNSENDT_TIDSPUNKT     TIMESTAMP(3)                           NOT NULL,
    AARSAK_TIL_OPPRETTELSE VARCHAR(50)                            NOT NULL,
);

CREATE TABLE MELDEKORT_PERIODE
(
    ID           BIGSERIAL PRIMARY KEY,
    MELDEKORT_ID BIGINT NOT NULL REFERENCES MELDEKORT (ID)
);

CREATE TABLE MELDEKORT_DAG
(
    ID                   BIGSERIAL PRIMARY KEY,
    MELDEKORT_PERIODE_ID BIGINT        NOT NULL REFERENCES MELDEKORT_PERIODE (ID),
    DATO                 DATE          NOT NULL,
    TIMER_ARBEIDET       NUMERIC(5, 2) NOT NULL
)
