ALTER TABLE TILKJENT_PERIODE
    drop column grunnlag;

CREATE TABLE BEREGNINGSGRUNNLAG
(
    ID            BIGSERIAL PRIMARY KEY,
    BEHANDLING_ID BIGINT         NOT NULL REFERENCES behandling,
    BELOP         NUMERIC(19, 2) NOT NULL
);