CREATE TABLE VEDTAK(
    ID BIGSERIAL PRIMARY KEY,
    FNR VARCHAR(11) NOT NULL,
    DAGSATS INTEGER NOT NULL,
    STATUS VARCHAR(255) NOT NULL,
    SAKSNUMMER VARCHAR(255) NOT NULL,
    VEDTAKSDATO DATE NOT NULL,
    PERIODE daterange NOT NULL,
    RETTIGHETS_TYPE VARCHAR(255) NOT NULL,
    BEREGNINGSGRUNNLAG INTEGER NOT NULL,
    BARN_MED_STONAD INTEGER NOT NULL,
    SAMORDNINGS_ID VARCHAR(255),
    OPPHORSORSAK VARCHAR(255),
    VEDTAKS_TYPE_KODE VARCHAR(255) NOT NULL,
    VEDTAKS_TYPE_NAVN VARCHAR(255) NOT NULL
);

CREATE TABLE UTBETALING(
    ID BIGSERIAL PRIMARY KEY,
    VEDTAK_ID BIGINT NOT NULL REFERENCES VEDTAK(ID),
    UTBETALINGSGRAD INTEGER NOT NULL,
    PERIODE daterange NOT NULL,
    BELOP INTEGER NOT NULL,
    DAGSATS INTEGER NOT NULL,
    BARNETILLEGG INTEGER NOT NULL
);

CREATE INDEX VEDTAK_ID_IDX ON UTBETALING(VEDTAK_ID);
CREATE INDEX FNR_IDX ON VEDTAK(FNR);