ALTER TABLE RETTIGHETSTYPE DROP CONSTRAINT rettighetstype_behandling_id_fkey,
ADD CONSTRAINT rettighetstype_behandling_id_fkey FOREIGN KEY (BEHANDLING_ID) REFERENCES BEHANDLING (ID) ON DELETE CASCADE;