openapi: "3.0.0"
info:
  title: AAP-api
  description: |-
    AAP-INTERN-API tilbyr et internt API for henting av AAP-data
    
    Bruker azure til autentisering
  contact:
    name: Team AAP
    url: https://github.com/navikt/aap-api-intern
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/license/mit/
tags:
  - name: perioder
    description: Henting av perioder
servers:
  - url: https://aap-api.intern.dev.nav.no
    description: Test server
paths:
  /perioder:
    post:
      summary: Hent perioder med AAP
      tags:
        - perioder
      description: |-
        Henter perioder med vedtak for en person innen gitte datointerval.
      security:
        - azure: [ ]
      parameters:
        - in: header
          name: x-callid
          description: En UUID konsumenten sender inn som brukes til videre logging og feilsøking.
          schema:
            type: string
            format: uuid
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PeriodeRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PeriodeResponse'
        '400':
          description: Feil i request
        '401':
          description: Mangler/feil token
        '403':
          description: Ikke tilgang
        '404':
          description: Manglende URL / Person ikke funnet
        '500':
          description: Feil på tjeneste, meld fra og send med call-id
  /perioder/aktivitetfase:
    post:
      summary: Hent perioder med AAP
      tags:
        - perioder
      description: |-
        Henter perioder med vedtak for en person innen gitte datointerval.
      security:
        - azure: [ ]
      parameters:
        - in: header
          name: x-callid
          description: En UUID konsumenten sender inn som brukes til videre logging og feilsøking.
          schema:
            type: string
            format: uuid
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PeriodeRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Periode11-17Response'
        '400':
          description: Feil i request
        '401':
          description: Mangler/feil token
        '403':
          description: Ikke tilgang
        '404':
          description: Manglende URL / Person ikke funnet
        '500':
          description: Feil på tjeneste, meld fra og send med call-id
  /sakerByFnr:
    post:
      summary: Hent alle AAP saker for personidentifikator
      tags:
        - saker
      description: |-
        Henter perioder med vedtak for en person innen gitte datointerval.
      security:
        - azure: [ ]
      parameters:
        - in: header
          name: x-callid
          description: En UUID konsumenten sender inn som brukes til videre logging og feilsøking.
          schema:
            type: string
            format: uuid
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SakerRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SakerStatus'
        '400':
          description: Feil i request
        '401':
          description: Mangler/feil token
        '403':
          description: Ikke tilgang
        '404':
          description: Manglende URL / Person ikke funnet
        '500':
          description: Feil på tjeneste, meld fra og send med call-id
components:
  schemas:
    PeriodeResponse:
      type: object
      properties:
        perioder:
          type: array
          description: Perioder med vedtak
          items:
            $ref: '#/components/schemas/Periode'
    Periode11-17Response:
      type: object
      properties:
        perioder:
          type: array
          description: Perioder med vedtak inkludert 11-17
          items:
            $ref: '#/components/schemas/PeriodeInkludert11_17'
    SakerRequest:
        type: object
        properties:
            personidentifikator:
              type: string
              description: Personnummeret til brukeren
              example: 12345678901
    SakerStatus:
        type: object
        properties:
            sakId:
              type: string
              description: SakId
              example: "<SakId>"
            sakStatus:
              type: string
              description: SakStatus
              example: "<SakStatus>"
            periode:
              $ref: '#/components/schemas/Periode'
    PeriodeInkludert11_17:
      type: object
      properties:
        aktivitetsfaseKode:
            type: string
            description: AktivitetsfaseKode
            example: "<KodeIString>"
        aktivitetsfaseNavn:
            type: string
            description: AktivitetsfaseNavn
            example: "<NavnIString>"
        periode:
          $ref: '#/components/schemas/Periode'
    Periode:
      type: object
      description: Periode
      properties:
        fraOgMedDato:
          type: string
          format: date
          description: Fra dato for perioden
          example: 2021-01-01
        tilOgMedDato:
          type: ['null', string]
          format: date
          nullable: true
          description: Til dato for perioden
          example: 2021-01-31
    PeriodeRequest:
      type: object
      properties:
        personidentifikator:
          type: string
          description: Personnummeret til brukeren
          example: 12345678901
        fraOgMedDato:
          type: string
          format: date
          description: Start-dato for ønsket uttak av AAP-perioder
          example: 2021-01-01
        tilOgMedDato:
          type: string
          format: date
          description: Slutt-dato for ønsket uttak av AAP-perioder
          example: 2021-01-01
  securitySchemes:
    azure:
      type: http
      scheme: bearer
      bearerFormat: JWT
