CREATE INDEX IDX_UNDERVEIS_BEHANDLING_ID ON UNDERVEIS (BEHANDLING_ID);

CREATE INDEX IDX_MELDEKORT_SAKSNUMMER ON MELDEKORT (SAKSNUMMER);
CREATE INDEX IDX_MELDEKORT_BEHANDLING_ID ON MELDEKORT (behandling_id);

CREATE INDEX IDX_TILKENT_PERIODE_TILKJENT_YTELSE_ID ON TILKJENT_PERIODE (tilkjent_ytelse_id);