ALTER TABLE TILKJENT_PERIODE
    ADD COLUMN EFFEKTIV_DAGSATS INT NULL;

ALTER TABLE MELDEKORT
    ADD COLUMN JOURNALPOST_ID TEXT NULL;

CREATE TABLE FRITAK_MELDEPLIKT
(
    ID            BIGSERIAL PRIMARY KEY,
    BEHANDLING_ID BIGINT    NOT NULL REFERENCES BEHANDLING (ID),
    PERIODE       DATERANGE NOT NULL
);

CREATE INDEX IDX_FRITAK_MELDEPLIKT_BEHANDLING_ID
    ON FRITAK_MELDEPLIKT (BEHANDLING_ID);

CREATE TABLE UNDERVEISPERIODE
(
    ID                BIGSERIAL PRIMARY KEY,
    BEHANDLING_ID     BIGINT        NOT NULL REFERENCES BEHANDLING (ID),
    PERIODE           DATERANGE     NOT NULL,
    MELDEPLIKTSTATUS  TEXT NULL,
    ARBEIDSGRAD       INT           NOT NULL,
    OVERGRENSE_VERDI  BOOLEAN       NOT NULL,
    TIMER_ARBEIDET    NUMERIC(5, 2) NOT NULL
);

CREATE INDEX IDX_UNDERVEISPERIODE_BEHANDLING_ID
    ON UNDERVEISPERIODE (BEHANDLING_ID);
