CREATE TABLE BEHANDLING_SAMID
(
    ID            BIGSERIAL PRIMARY KEY,
    BEHANDLING_ID BIGINT NOT NULL REFERENCES BEHANDLING (ID),
    SAMID         TEXT   NOT NULL,
    TPNR          TEXT
);

CREATE INDEX idx_behandling_samid_behandling_id ON BEHANDLING_SAMID (BEHANDLING_ID);

INSERT INTO BEHANDLING_SAMID (BEHANDLING_ID, SAMID)
SELECT ID, SAMID
FROM BEHANDLING
WHERE SAMID IS NOT NULL;

ALTER TABLE BEHANDLING
    DROP COLUMN SAMID;
