ALTER TABLE UNDERVEISPERIODE
    ADD COLUMN MELDEPERIODE DATERANGE;

UPDATE UNDERVEISPERIODE
SET MELDEPERIODE = PERIODE
WHERE MELDEPERIODE IS NULL;

ALTER TABLE UNDERVEISPERIODE
    ALTER COLUMN MELDEPERIODE SET NOT NULL;
