ALTER TABLE UNDERVEISPERIODE
    ADD COLUMN MELDEPERIODE DATERANGE;

DELETE FROM UNDERVEISPERIODE
WHERE MELDEPERIODE IS NULL;

ALTER TABLE UNDERVEISPERIODE
    ALTER COLUMN MELDEPERIODE SET NOT NULL;
