CREATE INDEX IDX_SAK ON SAK (SAKSNUMMER);

ALTER TABLE SAK_PERSON
    DROP CONSTRAINT sak_person_sak_id_fkey,
    ADD CONSTRAINT sak_person_sak_id_fkey FOREIGN KEY (SAK_ID) REFERENCES SAK (ID) ON DELETE CASCADE;

ALTER TABLE BEHANDLING
    DROP CONSTRAINT behandling_sak_id_fkey,
    ADD CONSTRAINT behandling_sak_id_fkey FOREIGN KEY (SAK_ID) REFERENCES SAK (ID) ON DELETE CASCADE;

ALTER TABLE UNDERVEIS
    DROP CONSTRAINT underveis_behandling_id_fkey,
    ADD CONSTRAINT underveis_behandling_id_fkey FOREIGN KEY (BEHANDLING_ID) REFERENCES BEHANDLING (ID) ON DELETE CASCADE;

ALTER TABLE TILKJENT_YTELSE
    DROP CONSTRAINT tilkjent_ytelse_behandling_id_fkey,
    ADD CONSTRAINT tilkjent_ytelse_behandling_id_fkey FOREIGN KEY (BEHANDLING_ID) REFERENCES BEHANDLING (ID) ON DELETE CASCADE;

ALTER TABLE TILKJENT_PERIODE
    DROP CONSTRAINT tilkjent_periode_tilkjent_ytelse_id_fkey,
    ADD CONSTRAINT tilkjent_periode_tilkjent_ytelse_id_fkey FOREIGN KEY (TILKJENT_YTELSE_ID) REFERENCES TILKJENT_YTELSE (ID) ON DELETE CASCADE;