CREATE TABLE RETTIGHETSTYPE
(
    ID   BIGSERIAL PRIMARY KEY,
    BEHANDLING_ID BIGINT NOT NULL REFERENCES BEHANDLING (ID),
    PERIODE DATERANGE NOT NULL,
    RETTIGHETSTYPE VARCHAR(100) NOT NULL
);

ALTER TABLE BEHANDLING ADD COLUMN BEHANDLING_REFERANSE VARCHAR(100) NOT NULL DEFAULT '',
ADD COLUMN BEHANDLINGSTYPE VARCHAR(100) NOT NULL DEFAULT '';

ALTER TABLE BEHANDLING ALTER COLUMN BEHANDLING_REFERANSE DROP DEFAULT;