apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: api-alerts
  labels:
    team: aap
    app: api
  namespace: aap
spec:
  groups:
    - name:  api-alerts
      rules:
        - alert: InstanceDown
          expr: kube_deployment_status_replicas_unavailable{deployment="api",job="kubernetes-service-endpoints"} > 0
          for: 5m
          annotations:
            consequence: "api har utilgjengelige podder i aap"
            action: "kubectl describe pod -l app=api -n aap` for events og `kubectl get pods -l app=api -n aap` for å se feilende podder"
          labels:
            severity: critical
        - alert: IntancesRestarting
          expr: sum(increase(kube_pod_container_status_restarts_total{container=~"api"}[5m])) by (container) > 2
          for: 2m
          annotations:
            consequence: "api har restartet flere ganger de siste 5 minuttene!"
            action: "Se `kubectl describe pod api` for events, og `kubectl logs api` for logger"
          labels:
            severity: critical
        -   alert: MissingMetrics
            expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="api",log_level=~"Error"}[10m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="api"}[10m]))) > 15
            for: 5m
            annotations:
              consequence: "api rapporterer ingen metrikker i aap"
              action: "Sjekk om soknad-api i aap er oppe"
            labels:
              severity: critical