name: Deploy alerts to prod and dev
on:
  push:
    branches:
      - 'main'
    paths:
      - "*-gcp-alerts.yml"

jobs:
  deploy-to-dev-and-prod:
    name: Deploy to ${{ matrix.cluster }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster: [dev-gcp, prod-gcp]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: .github/alerts/${{ matrix.cluster }}-alerts.yml